name = "RobustLikelihoodModel"
uuid = "b6af87c3-da32-4dab-8f19-2929dfcada29"
authors = ["Austin Garrett <agarret7@mit.edu>"]
version = "0.1.0"

[deps]
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
